### ISSUE TITLE
how to adjust image slider window according image size

### ISSUE THREAD

**Issue by sherurulz** [palerdot/albumize#1]
I have been using this jquery for a project of mine. Can you please tell me how to adjust image slider window size according to the image size(dimensions).

Thank you.

**Comment by palerdot** [comment]
Can you give more information ? Like a screenshot ? I'm not sure if it is an issue or a requirement. Thanks.

**Comment by palerdot** [comment]
I'm closing this since it seems like a requirement and not an issue.
